modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="general_life"
version="1.0.0"
displayName="general_life"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Daniel1394"

[[dependencies.general_life]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



